### ISSUE TITLE
Add a flag for the user to decide to show trajectory conflicts and negotiations

### ISSUE THREAD

**Issue by matiasbavera** [osrf/rmf-web#206]
The idea is to have trajectory conflicts and negotiations completely hidden except when the user specifically opens some kind of panel to look at that information (or maybe activate a flag). We don't generally need to report failed negotiations. 

Regarding repeatedly failing negotiations
We could have a separate error channel for escalating repeatedly failing negotiations to the operator's attention, and that message could be channeled into an operator notification.

**Comment by koonpeng** [comment]
I think we should always show trajectory conflicts, but not the snack bar alert. Trajectory conflicts are considered normal operations in rmf so it should not raise any attention. Only when a robot failed to resolve the conflict after a certain amount of time then we consider it abnormal, but this requires a server to keep track of that data.

For negotiation, I thought the original design is to only show it when the negotiation panel is opened. There shouldn't be a need to show the negotiation trajectories layer checkbox in leaflet. It will always show when the user is in the negotiation panel and be hidden otherwise, all normal trajectories will also be hidden when we are showing negotiation trajectories. It looks like the design never got in so this change would be very welcomed.

**Comment by matiasbavera** [comment]
Ok, thanks for the feedback. I'll update the description.






> For negotiation, I thought the original design is to only show it when the negotiation panel is opened. There shouldn't be a need to show the negotiation trajectories layer checkbox in leaflet. It will always show when the user is in the negotiation panel and be hidden otherwise, all normal trajectories will also be hidden when we are showing negotiation trajectories. It looks like the design never got in so this change would be very welcomed.

Yeah, that was the idea. Oh yeah, the negotiation trajectories are showed on top of the current trajectories, only when you click on a negotiation item (on the Omni-panel). So, if I understand correctly, the idea is to remove the current trajectory from the map and just show the negotiation when a negotiation is clicked, right?

**Comment by matiasbavera** [comment]
> I think we should always show trajectory conflicts, but not the snack bar alert.

Got it. I think we should remove the snack alert when we implement the "grid" UI. But we can hide it with a flag for now

**Comment by koonpeng** [comment]
fixed by #222
